version: '3.9'
 
services:
  php-env : 
    build: ./src
    volumes:
        - ./src:/var/www/html
    ports:
        - 80:80

  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BORNES

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1    
        
volumes:
    db_data: